global:
  source: '_src'
  destination: '_dist'
  metadata:
    baseurl: 'http://localhost:3000/'
    sitename: 'Thesis Blog'
    description: 'A blog featuring the progress of my Master thesis project.'
    author: 'Sascha Zarhuber'
    generatorname: 'ContentCrane powered by Metalsmith'

exclude:

date-in-filename:
  override: true

metadata-directory:
  directory: _data/*.json

drafts: true

markdown: true

excerpts: true

assets:
  source: ./_public
  destination: ./assets

sass:
  outputStyle: compressed
  outputDir: assets/css
  sourceMap: true
  sourceMapContents: true

collections:
  blog: posts/*.md
  repos: repos/*.md

permalinks:
  relative: false
  pattern: ':title'
  date: 'YYYY/MM/DD'
  linksets:
    - match:
        collection: blog
      pattern: blog/:date/:title
    - match:
        collection: repos
      pattern: repos/:hash

layouts:
  engine: handlebars
  directory: _layouts
  partials: _includes
  default: default.hbs
  pattern:
    - "**/*.hbs"
    - "**/*.html"
    - "**/*.md"
  rename: true
